steps:
  - [python, make_data.py]
  - [python, train.py]

outputs:
  data:
    type: folder
  repo:
    type: repo
    lines:
      baseline_logreg:
        type: model_line
        len: 3
        metrics:
          f1_score: {min: 0.0, max: 1.0}
          accuracy_score: {min: 0.0, max: 1.0}
          roc_auc_score: {min: 0.0, max: 1.0}

      baseline_tree:
        type: model_line
        len: 3
        metrics:
          f1_score: {min: 0.0, max: 1.0}
          accuracy_score: {min: 0.0, max: 1.0}
          roc_auc_score: {min: 0.0, max: 1.0}
