steps:
  - [python3, make_data.py]
  - [python3, version_data.py]
  - [python3, train_on_version.py]
outputs:
  repo:
    type: repo
    lines:
      dataline:
        type: data_line
        len: 4

      ticket_router:
        type: model_line
        len: 2
        metrics:
          accuracy_score: {min: 0.0, max: 1.0}
